### ISSUE TITLE
pool.join throws

### ISSUE THREAD

**Issue by paleozogt** [meh/ruby-thread#31]
Using ```pool.join``` throws.  For example this code:
```
require 'thread/pool'

pool = Thread.pool(4)

10.times {
  pool.process {
    sleep 2

    puts 'lol'
  }
}

pool.join
```

produces this output:

```
lol
lol
lol
lol
lollol
lol
lol

lol
lol
/Library/Ruby/Gems/2.0.0/gems/thread-0.1.5/lib/thread/pool.rb:310:in `join': No live threads left. Deadlock? (fatal)
	from /Library/Ruby/Gems/2.0.0/gems/thread-0.1.5/lib/thread/pool.rb:310:in `join'
	from ./aws_ruby.rb:14:in `<main>'
```

**Comment by meh** [comment]
MRI I assume? It's a problem with MRI's deadlock checker.

**Comment by paleozogt** [comment]
Yes:
```
$ ruby --version
ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin13]
```

What's curious is that ```pool.shutdown``` works, which presumably is doing some kind of join.

**Comment by meh** [comment]
Removed `#join` altogether in 0.2.0 because it was pointless.
