### ISSUE TITLE
Cannot shutdown thread pool

### ISSUE THREAD

**Issue by ivoanjo** [meh/ruby-thread#35]
Testcase:
```ruby
require 'thread/pool'

pool = Thread.pool(4)
sleep(1)
pool.shutdown
```

Output:
```
$ bundle exec ruby pool-issue.rb 
/home/knuckles/.rvm/gems/ruby-2.0.0-p598/gems/thread-0.1.6/lib/thread/pool.rb:194:in `synchronize': deadlock; recursive locking (ThreadError)
        from /home/knuckles/.rvm/gems/ruby-2.0.0-p598/gems/thread-0.1.6/lib/thread/pool.rb:194:in `done?'
        from /home/knuckles/.rvm/gems/ruby-2.0.0-p598/gems/thread-0.1.6/lib/thread/pool.rb:452:in `block in report_done'
        from /home/knuckles/.rvm/gems/ruby-2.0.0-p598/gems/thread-0.1.6/lib/thread/pool.rb:451:in `synchronize'
        from /home/knuckles/.rvm/gems/ruby-2.0.0-p598/gems/thread-0.1.6/lib/thread/pool.rb:451:in `report_done'
        from /home/knuckles/.rvm/gems/ruby-2.0.0-p598/gems/thread-0.1.6/lib/thread/pool.rb:378:in `block (3 levels) in spawn_thread'
        from /home/knuckles/.rvm/gems/ruby-2.0.0-p598/gems/thread-0.1.6/lib/thread/pool.rb:365:in `synchronize'
        from /home/knuckles/.rvm/gems/ruby-2.0.0-p598/gems/thread-0.1.6/lib/thread/pool.rb:365:in `block (2 levels) in spawn_thread'
        from /home/knuckles/.rvm/gems/ruby-2.0.0-p598/gems/thread-0.1.6/lib/thread/pool.rb:364:in `loop'
        from /home/knuckles/.rvm/gems/ruby-2.0.0-p598/gems/thread-0.1.6/lib/thread/pool.rb:364:in `block in spawn_thread'
```

May have same cause as issue #34 , but not sure.

**Comment by meh** [comment]
Checking on it, I just realized there are no tests for the pool.

**Comment by meh** [comment]
See #34
