### ISSUE TITLE
[v 0.1.6] ThreadError: deadlock; recursive locking 

### ISSUE THREAD

**Issue by edposnak** [meh/ruby-thread#36]
Running on MRI ruby 2.2.1p85 we started getting "ThreadError: deadlock; recursive locking" after upgrading from v0.1.5 to v0.1.6.  The error goes away when reverting to v0.1.5. 

Here is the backtrace, which seems related to recent changes in pool.rb
```
ThreadError: deadlock; recursive locking
thread-0.1.6/lib/thread/pool.rb:194:in `synchronize'
thread-0.1.6/lib/thread/pool.rb:194:in `done?'
thread-0.1.6/lib/thread/pool.rb:452:in `block in report_done'
thread-0.1.6/lib/thread/pool.rb:451:in `synchronize'
thread-0.1.6/lib/thread/pool.rb:451:in `report_done'
thread-0.1.6/lib/thread/pool.rb:378:in `block (3 levels) in spawn_thread'
thread-0.1.6/lib/thread/pool.rb:365:in `synchronize'
thread-0.1.6/lib/thread/pool.rb:365:in `block (2 levels) in spawn_thread'
thread-0.1.6/lib/thread/pool.rb:364:in `loop'
thread-0.1.6/lib/thread/pool.rb:364:in `block in spawn_thread'
```

**Comment by meh** [comment]
Checking on it, I just realized there are no tests for the pool.

**Comment by meh** [comment]
See #34
