### ISSUE TITLE
`Thread::Pool::Task` leaks

### ISSUE THREAD

**Issue by forresty** [meh/ruby-thread#39]
```ruby
#!/usr/bin/env ruby

require 'sigdump/setup'
require 'thread/pool'

puts "process started with pid: #{Process.pid}"

sum = 0

pool = Thread.pool(4) { |i| sum += i }

loop do
  1000.times { |i| pool.process(i) }

  GC.start
  sleep 30
end
```

kill the process with `kill -CONT pid`, we have sigdump result as following:

```shell
Sigdump at 2015-07-08 23:34:16 +0800 process 4530 (./leak.rb)
  Thread #<Thread:0x007f8e5a0c03b0> status=run priority=0
      /Users/forresty/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sigdump-0.2.3/lib/sigdump.rb:39:in `backtrace'
      /Users/forresty/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sigdump-0.2.3/lib/sigdump.rb:39:in `dump_backtrace'
      /Users/forresty/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sigdump-0.2.3/lib/sigdump.rb:25:in `block in dump_all_thread_backtrace'
      /Users/forresty/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sigdump-0.2.3/lib/sigdump.rb:24:in `each'
      /Users/forresty/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sigdump-0.2.3/lib/sigdump.rb:24:in `dump_all_thread_backtrace'
      /Users/forresty/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sigdump-0.2.3/lib/sigdump.rb:16:in `block in dump'
      /Users/forresty/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sigdump-0.2.3/lib/sigdump.rb:119:in `open'
      /Users/forresty/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sigdump-0.2.3/lib/sigdump.rb:119:in `_open_dump_path'
      /Users/forresty/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sigdump-0.2.3/lib/sigdump.rb:14:in `dump'
      /Users/forresty/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sigdump-0.2.3/lib/sigdump.rb:7:in `block in setup'
      ./leak.rb:16:in `call'
      ./leak.rb:16:in `sleep'
      ./leak.rb:16:in `block in <main>'
      ./leak.rb:12:in `loop'
      ./leak.rb:12:in `<main>'
  Thread #<Thread:0x007f8e5a082ee8> status=sleep priority=0
      /Users/forresty/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thread-0.2.0/lib/thread/pool.rb:393:in `sleep'
      /Users/forresty/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thread-0.2.0/lib/thread/pool.rb:393:in `wait'
      /Users/forresty/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thread-0.2.0/lib/thread/pool.rb:393:in `block (3 levels) in spawn_thread'
      /Users/forresty/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thread-0.2.0/lib/thread/pool.rb:373:in `synchronize'
      /Users/forresty/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thread-0.2.0/lib/thread/pool.rb:373:in `block (2 levels) in spawn_thread'
      /Users/forresty/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thread-0.2.0/lib/thread/pool.rb:372:in `loop'
      /Users/forresty/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thread-0.2.0/lib/thread/pool.rb:372:in `block in spawn_thread'
  Thread #<Thread:0x007f8e5a082d08> status=sleep priority=0
      /Users/forresty/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thread-0.2.0/lib/thread/pool.rb:393:in `sleep'
      /Users/forresty/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thread-0.2.0/lib/thread/pool.rb:393:in `wait'
      /Users/forresty/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thread-0.2.0/lib/thread/pool.rb:393:in `block (3 levels) in spawn_thread'
      /Users/forresty/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thread-0.2.0/lib/thread/pool.rb:373:in `synchronize'
      /Users/forresty/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thread-0.2.0/lib/thread/pool.rb:373:in `block (2 levels) in spawn_thread'
      /Users/forresty/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thread-0.2.0/lib/thread/pool.rb:372:in `loop'
      /Users/forresty/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thread-0.2.0/lib/thread/pool.rb:372:in `block in spawn_thread'
  Thread #<Thread:0x007f8e5a082b28> status=sleep priority=0
      /Users/forresty/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thread-0.2.0/lib/thread/pool.rb:393:in `sleep'
      /Users/forresty/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thread-0.2.0/lib/thread/pool.rb:393:in `wait'
      /Users/forresty/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thread-0.2.0/lib/thread/pool.rb:393:in `block (3 levels) in spawn_thread'
      /Users/forresty/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thread-0.2.0/lib/thread/pool.rb:373:in `synchronize'
      /Users/forresty/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thread-0.2.0/lib/thread/pool.rb:373:in `block (2 levels) in spawn_thread'
      /Users/forresty/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thread-0.2.0/lib/thread/pool.rb:372:in `loop'
      /Users/forresty/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thread-0.2.0/lib/thread/pool.rb:372:in `block in spawn_thread'
  Thread #<Thread:0x007f8e5a082970> status=sleep priority=0
      /Users/forresty/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thread-0.2.0/lib/thread/pool.rb:393:in `sleep'
      /Users/forresty/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thread-0.2.0/lib/thread/pool.rb:393:in `wait'
      /Users/forresty/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thread-0.2.0/lib/thread/pool.rb:393:in `block (3 levels) in spawn_thread'
      /Users/forresty/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thread-0.2.0/lib/thread/pool.rb:373:in `synchronize'
      /Users/forresty/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thread-0.2.0/lib/thread/pool.rb:373:in `block (2 levels) in spawn_thread'
      /Users/forresty/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thread-0.2.0/lib/thread/pool.rb:372:in `loop'
      /Users/forresty/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thread-0.2.0/lib/thread/pool.rb:372:in `block in spawn_thread'
  GC stat:
      count: 9
      heap_allocated_pages: 74
      heap_sorted_length: 75
      heap_allocatable_pages: 0
      heap_available_slots: 30161
      heap_live_slots: 18598
      heap_free_slots: 11563
      heap_final_slots: 0
      heap_marked_slots: 17398
      heap_swept_slots: 12762
      heap_eden_pages: 74
      heap_tomb_pages: 0
      total_allocated_pages: 74
      total_freed_pages: 0
      total_allocated_objects: 103524
      total_freed_objects: 84926
      malloc_increase_bytes: 109520
      malloc_increase_bytes_limit: 16777216
      minor_gc_count: 5
      major_gc_count: 4
      remembered_wb_unprotected_objects: 190
      remembered_wb_unprotected_objects_limit: 380
      old_objects: 15195
      old_objects_limit: 30390
      oldmalloc_increase_bytes: 109904
      oldmalloc_increase_bytes_limit: 16777216
  Built-in objects:
    30,161: TOTAL
    11,457: FREE
    10,276: T_STRING
     3,146: T_ARRAY
     1,970: T_OBJECT
     1,877: T_DATA
       530: T_CLASS
       506: T_NODE
       267: T_HASH
        68: T_REGEXP
        27: T_ICLASS
        23: T_MODULE
         4: T_FILE
         4: T_FLOAT
         3: T_STRUCT
         2: T_BIGNUM
         1: T_COMPLEX
  All objects:
    10,446: String
     2,813: Array
     1,006: Time
       968: Thread::Pool::Task
       708: RubyVM::InstructionSequence
       264: Hash
       249: Class
       211: Gem::Version
       208: Gem::StubSpecification
       205: Gem::StubSpecification::StubLine
       204: Gem::Requirement
       124: Gem::Dependency
       100: Encoding
        68: Regexp
        39: Gem::Specification
        23: Module
        17: Proc
        12: RubyVM::Env
        12: MatchData
         7: Mutex
         5: Thread::Backtrace
         5: Thread
         4: Float
         3: IO
         3: Object
         2: Thread::ConditionVariable
         2: Bignum
         1: Thread::Pool
         1: IOError
         1: Binding
         1: RubyVM
         1: NoMemoryError
         1: SystemStackError
         1: Random
         1: ARGF.class
         1: Complex
         1: Data
         1: ThreadGroup
         1: File
         1: fatal
         1: Gem::Platform
         1: Monitor
         1: Gem::PathSupport
         1: Range
  String 281,685 bytes
   Array 2 elements
    Hash 2 pairs
```

We now have  968 Thread::Pool::Task

Ruby version:

```shell
$ ruby -v
ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin13]
```

Found on some other Ruby versions as well. Read the source code of `thread` gem, no idea why yet

**Comment by forresty** [comment]
and following was found on a long running process in one of our services:

```shell
Mutex:21825
Thread::Pool::Task:21732
Thread::Future:21710
RubyVM::InstructionSequence:8440
```

**Comment by meh** [comment]
Looking into it.

Were the `Thread::Future` used withing a `Thread::Pool` or just by themselves?

**Comment by forresty** [comment]
@meh within a `Thread::Pool`

`RDKit` is a small toolkit I wrote, and we've built some long running processes on top of it

the problematic code is here:

https://github.com/forresty/rdkit/blob/master/lib/rdkit/client.rb#L38

**Comment by meh** [comment]
I've been testing the example code you provided in the opening comment, and the leak is actually not a leak, at least in that code.

If you keep getting sigdumps and reduce the wait time, you'll see the number of tasks stays constant, that's because they're pushed onto the todo list and kept there until they're executed.

To avoid that *leak* you'd have to wait for the pool to be idle, and you can do that with `pool.wait.process(i)` in that small example.

```ruby
#!/usr/bin/env ruby

require 'sigdump/setup'
require 'thread/pool'

puts "process started with pid: #{Process.pid}"

sum = 0

pool = Thread.pool(4) { |i| sum += i }

loop do
  1000.times { |i| pool.wait.process(i) }

  GC.start
  sleep 5
end
```

```
Sigdump at 2015-07-08 18:34:29 +0200 process 30127 (/tmp/lol.rb)
  Thread #<Thread:0x000000024172e0> status=run priority=0
      /home/meh/.gem/ruby/2.2.0/gems/sigdump-0.2.3/lib/sigdump.rb:39:in `backtrace'
      /home/meh/.gem/ruby/2.2.0/gems/sigdump-0.2.3/lib/sigdump.rb:39:in `dump_backtrace'
      /home/meh/.gem/ruby/2.2.0/gems/sigdump-0.2.3/lib/sigdump.rb:25:in `block in dump_all_thread_backtrace'
      /home/meh/.gem/ruby/2.2.0/gems/sigdump-0.2.3/lib/sigdump.rb:24:in `each'
      /home/meh/.gem/ruby/2.2.0/gems/sigdump-0.2.3/lib/sigdump.rb:24:in `dump_all_thread_backtrace'
      /home/meh/.gem/ruby/2.2.0/gems/sigdump-0.2.3/lib/sigdump.rb:16:in `block in dump'
      /home/meh/.gem/ruby/2.2.0/gems/sigdump-0.2.3/lib/sigdump.rb:119:in `open'
      /home/meh/.gem/ruby/2.2.0/gems/sigdump-0.2.3/lib/sigdump.rb:119:in `_open_dump_path'
      /home/meh/.gem/ruby/2.2.0/gems/sigdump-0.2.3/lib/sigdump.rb:14:in `dump'
      /home/meh/.gem/ruby/2.2.0/gems/sigdump-0.2.3/lib/sigdump.rb:7:in `block in setup'
      /tmp/lol.rb:16:in `call'
      /tmp/lol.rb:16:in `sleep'
      /tmp/lol.rb:16:in `block in <main>'
      /tmp/lol.rb:12:in `loop'
      /tmp/lol.rb:12:in `<main>'
  Thread #<Thread:0x000000026d9500> status=sleep priority=0
      /home/meh/.gem/ruby/2.2.0/gems/thread-0.2.0/lib/thread/pool.rb:393:in `sleep'
      /home/meh/.gem/ruby/2.2.0/gems/thread-0.2.0/lib/thread/pool.rb:393:in `wait'
      /home/meh/.gem/ruby/2.2.0/gems/thread-0.2.0/lib/thread/pool.rb:393:in `block (3 levels) in spawn_thread'
      /home/meh/.gem/ruby/2.2.0/gems/thread-0.2.0/lib/thread/pool.rb:373:in `synchronize'
      /home/meh/.gem/ruby/2.2.0/gems/thread-0.2.0/lib/thread/pool.rb:373:in `block (2 levels) in spawn_thread'
      /home/meh/.gem/ruby/2.2.0/gems/thread-0.2.0/lib/thread/pool.rb:372:in `loop'
      /home/meh/.gem/ruby/2.2.0/gems/thread-0.2.0/lib/thread/pool.rb:372:in `block in spawn_thread'
  Thread #<Thread:0x000000026d92a8> status=sleep priority=0
      /home/meh/.gem/ruby/2.2.0/gems/thread-0.2.0/lib/thread/pool.rb:393:in `sleep'
      /home/meh/.gem/ruby/2.2.0/gems/thread-0.2.0/lib/thread/pool.rb:393:in `wait'
      /home/meh/.gem/ruby/2.2.0/gems/thread-0.2.0/lib/thread/pool.rb:393:in `block (3 levels) in spawn_thread'
      /home/meh/.gem/ruby/2.2.0/gems/thread-0.2.0/lib/thread/pool.rb:373:in `synchronize'
      /home/meh/.gem/ruby/2.2.0/gems/thread-0.2.0/lib/thread/pool.rb:373:in `block (2 levels) in spawn_thread'
      /home/meh/.gem/ruby/2.2.0/gems/thread-0.2.0/lib/thread/pool.rb:372:in `loop'
      /home/meh/.gem/ruby/2.2.0/gems/thread-0.2.0/lib/thread/pool.rb:372:in `block in spawn_thread'
  Thread #<Thread:0x000000026d8fb0> status=sleep priority=0
      /home/meh/.gem/ruby/2.2.0/gems/thread-0.2.0/lib/thread/pool.rb:393:in `sleep'
      /home/meh/.gem/ruby/2.2.0/gems/thread-0.2.0/lib/thread/pool.rb:393:in `wait'
      /home/meh/.gem/ruby/2.2.0/gems/thread-0.2.0/lib/thread/pool.rb:393:in `block (3 levels) in spawn_thread'
      /home/meh/.gem/ruby/2.2.0/gems/thread-0.2.0/lib/thread/pool.rb:373:in `synchronize'
      /home/meh/.gem/ruby/2.2.0/gems/thread-0.2.0/lib/thread/pool.rb:373:in `block (2 levels) in spawn_thread'
      /home/meh/.gem/ruby/2.2.0/gems/thread-0.2.0/lib/thread/pool.rb:372:in `loop'
      /home/meh/.gem/ruby/2.2.0/gems/thread-0.2.0/lib/thread/pool.rb:372:in `block in spawn_thread'
  Thread #<Thread:0x000000026d8a38> status=sleep priority=0
      /home/meh/.gem/ruby/2.2.0/gems/thread-0.2.0/lib/thread/pool.rb:393:in `sleep'
      /home/meh/.gem/ruby/2.2.0/gems/thread-0.2.0/lib/thread/pool.rb:393:in `wait'
      /home/meh/.gem/ruby/2.2.0/gems/thread-0.2.0/lib/thread/pool.rb:393:in `block (3 levels) in spawn_thread'
      /home/meh/.gem/ruby/2.2.0/gems/thread-0.2.0/lib/thread/pool.rb:373:in `synchronize'
      /home/meh/.gem/ruby/2.2.0/gems/thread-0.2.0/lib/thread/pool.rb:373:in `block (2 levels) in spawn_thread'
      /home/meh/.gem/ruby/2.2.0/gems/thread-0.2.0/lib/thread/pool.rb:372:in `loop'
      /home/meh/.gem/ruby/2.2.0/gems/thread-0.2.0/lib/thread/pool.rb:372:in `block in spawn_thread'
  GC stat:
      count: 8
      heap_allocated_pages: 74
      heap_sorted_length: 75
      heap_allocatable_pages: 0
      heap_available_slots: 30160
      heap_live_slots: 12047
      heap_free_slots: 18113
      heap_final_slots: 0
      heap_marked_slots: 11812
      heap_swept_slots: 18347
      heap_eden_pages: 74
      heap_tomb_pages: 0
      total_allocated_pages: 74
      total_freed_pages: 0
      total_allocated_objects: 75555
      total_freed_objects: 63508
      malloc_increase_bytes: 29992
      malloc_increase_bytes_limit: 16777216
      minor_gc_count: 4
      major_gc_count: 4
      remembered_wb_unprotected_objects: 171
      remembered_wb_unprotected_objects_limit: 342
      old_objects: 11540
      old_objects_limit: 23080
      oldmalloc_increase_bytes: 30440
      oldmalloc_increase_bytes_limit: 16777216
  Built-in objects:
    30,160: TOTAL
    18,007: FREE
     7,996: T_STRING
     1,346: T_ARRAY
       896: T_DATA
       596: T_CLASS
       525: T_OBJECT
       506: T_NODE
       156: T_HASH
        68: T_REGEXP
        27: T_ICLASS
        23: T_MODULE
         4: T_FLOAT
         4: T_FILE
         3: T_STRUCT
         2: T_BIGNUM
         1: T_COMPLEX
  All objects:
     8,158: String
     1,014: Array
       708: RubyVM::InstructionSequence
       282: Class
       153: Hash
       133: Gem::Version
       115: Gem::StubSpecification
       112: Gem::StubSpecification::StubLine
       100: Encoding
        85: Gem::Requirement
        68: Regexp
        43: Gem::Dependency
        25: Time
        23: Module
        20: Gem::Specification
        17: Proc
        12: RubyVM::Env
         8: MatchData
         7: Mutex
         6: Thread::Pool::Task
         5: Thread::Backtrace
         5: Thread
         4: Float
         3: IO
         3: Object
         2: Bignum
         2: Thread::ConditionVariable
         1: File
         1: Complex
         1: ThreadGroup
         1: IOError
         1: Binding
         1: RubyVM
         1: NoMemoryError
         1: SystemStackError
         1: Random
         1: ARGF.class
         1: Data
         1: fatal
         1: Thread::Pool
         1: Range
         1: Gem::Platform
         1: Monitor
         1: Gem::PathSupport
  String 158,032 bytes
   Array 4 elements
    Hash 1 pairs
Sigdump at 2015-07-08 18:34:45 +0200 process 30127 (/tmp/lol.rb)
  Thread #<Thread:0x000000024172e0> status=run priority=0
      /home/meh/.gem/ruby/2.2.0/gems/sigdump-0.2.3/lib/sigdump.rb:39:in `backtrace'
      /home/meh/.gem/ruby/2.2.0/gems/sigdump-0.2.3/lib/sigdump.rb:39:in `dump_backtrace'
      /home/meh/.gem/ruby/2.2.0/gems/sigdump-0.2.3/lib/sigdump.rb:25:in `block in dump_all_thread_backtrace'
      /home/meh/.gem/ruby/2.2.0/gems/sigdump-0.2.3/lib/sigdump.rb:24:in `each'
      /home/meh/.gem/ruby/2.2.0/gems/sigdump-0.2.3/lib/sigdump.rb:24:in `dump_all_thread_backtrace'
      /home/meh/.gem/ruby/2.2.0/gems/sigdump-0.2.3/lib/sigdump.rb:16:in `block in dump'
      /home/meh/.gem/ruby/2.2.0/gems/sigdump-0.2.3/lib/sigdump.rb:119:in `open'
      /home/meh/.gem/ruby/2.2.0/gems/sigdump-0.2.3/lib/sigdump.rb:119:in `_open_dump_path'
      /home/meh/.gem/ruby/2.2.0/gems/sigdump-0.2.3/lib/sigdump.rb:14:in `dump'
      /home/meh/.gem/ruby/2.2.0/gems/sigdump-0.2.3/lib/sigdump.rb:7:in `block in setup'
      /tmp/lol.rb:16:in `call'
      /tmp/lol.rb:16:in `sleep'
      /tmp/lol.rb:16:in `block in <main>'
      /tmp/lol.rb:12:in `loop'
      /tmp/lol.rb:12:in `<main>'
  Thread #<Thread:0x000000026d9500> status=sleep priority=0
      /home/meh/.gem/ruby/2.2.0/gems/thread-0.2.0/lib/thread/pool.rb:393:in `sleep'
      /home/meh/.gem/ruby/2.2.0/gems/thread-0.2.0/lib/thread/pool.rb:393:in `wait'
      /home/meh/.gem/ruby/2.2.0/gems/thread-0.2.0/lib/thread/pool.rb:393:in `block (3 levels) in spawn_thread'
      /home/meh/.gem/ruby/2.2.0/gems/thread-0.2.0/lib/thread/pool.rb:373:in `synchronize'
      /home/meh/.gem/ruby/2.2.0/gems/thread-0.2.0/lib/thread/pool.rb:373:in `block (2 levels) in spawn_thread'
      /home/meh/.gem/ruby/2.2.0/gems/thread-0.2.0/lib/thread/pool.rb:372:in `loop'
      /home/meh/.gem/ruby/2.2.0/gems/thread-0.2.0/lib/thread/pool.rb:372:in `block in spawn_thread'
  Thread #<Thread:0x000000026d92a8> status=sleep priority=0
      /home/meh/.gem/ruby/2.2.0/gems/thread-0.2.0/lib/thread/pool.rb:393:in `sleep'
      /home/meh/.gem/ruby/2.2.0/gems/thread-0.2.0/lib/thread/pool.rb:393:in `wait'
      /home/meh/.gem/ruby/2.2.0/gems/thread-0.2.0/lib/thread/pool.rb:393:in `block (3 levels) in spawn_thread'
      /home/meh/.gem/ruby/2.2.0/gems/thread-0.2.0/lib/thread/pool.rb:373:in `synchronize'
      /home/meh/.gem/ruby/2.2.0/gems/thread-0.2.0/lib/thread/pool.rb:373:in `block (2 levels) in spawn_thread'
      /home/meh/.gem/ruby/2.2.0/gems/thread-0.2.0/lib/thread/pool.rb:372:in `loop'
      /home/meh/.gem/ruby/2.2.0/gems/thread-0.2.0/lib/thread/pool.rb:372:in `block in spawn_thread'
  Thread #<Thread:0x000000026d8fb0> status=sleep priority=0
      /home/meh/.gem/ruby/2.2.0/gems/thread-0.2.0/lib/thread/pool.rb:393:in `sleep'
      /home/meh/.gem/ruby/2.2.0/gems/thread-0.2.0/lib/thread/pool.rb:393:in `wait'
      /home/meh/.gem/ruby/2.2.0/gems/thread-0.2.0/lib/thread/pool.rb:393:in `block (3 levels) in spawn_thread'
      /home/meh/.gem/ruby/2.2.0/gems/thread-0.2.0/lib/thread/pool.rb:373:in `synchronize'
      /home/meh/.gem/ruby/2.2.0/gems/thread-0.2.0/lib/thread/pool.rb:373:in `block (2 levels) in spawn_thread'
      /home/meh/.gem/ruby/2.2.0/gems/thread-0.2.0/lib/thread/pool.rb:372:in `loop'
      /home/meh/.gem/ruby/2.2.0/gems/thread-0.2.0/lib/thread/pool.rb:372:in `block in spawn_thread'
  Thread #<Thread:0x000000026d8a38> status=sleep priority=0
      /home/meh/.gem/ruby/2.2.0/gems/thread-0.2.0/lib/thread/pool.rb:393:in `sleep'
      /home/meh/.gem/ruby/2.2.0/gems/thread-0.2.0/lib/thread/pool.rb:393:in `wait'
      /home/meh/.gem/ruby/2.2.0/gems/thread-0.2.0/lib/thread/pool.rb:393:in `block (3 levels) in spawn_thread'
      /home/meh/.gem/ruby/2.2.0/gems/thread-0.2.0/lib/thread/pool.rb:373:in `synchronize'
      /home/meh/.gem/ruby/2.2.0/gems/thread-0.2.0/lib/thread/pool.rb:373:in `block (2 levels) in spawn_thread'
      /home/meh/.gem/ruby/2.2.0/gems/thread-0.2.0/lib/thread/pool.rb:372:in `loop'
      /home/meh/.gem/ruby/2.2.0/gems/thread-0.2.0/lib/thread/pool.rb:372:in `block in spawn_thread'
  GC stat:
      count: 12
      heap_allocated_pages: 74
      heap_sorted_length: 75
      heap_allocatable_pages: 0
      heap_available_slots: 30160
      heap_live_slots: 12088
      heap_free_slots: 18072
      heap_final_slots: 0
      heap_marked_slots: 11894
      heap_swept_slots: 18265
      heap_eden_pages: 74
      heap_tomb_pages: 0
      total_allocated_pages: 74
      total_freed_pages: 0
      total_allocated_objects: 100602
      total_freed_objects: 88514
      malloc_increase_bytes: 24160
      malloc_increase_bytes_limit: 16777216
      minor_gc_count: 4
      major_gc_count: 8
      remembered_wb_unprotected_objects: 180
      remembered_wb_unprotected_objects_limit: 360
      old_objects: 11667
      old_objects_limit: 23334
      oldmalloc_increase_bytes: 24608
      oldmalloc_increase_bytes_limit: 16777216
  Built-in objects:
    30,160: TOTAL
    17,966: FREE
     8,024: T_STRING
     1,351: T_ARRAY
       900: T_DATA
       596: T_CLASS
       528: T_OBJECT
       506: T_NODE
       157: T_HASH
        68: T_REGEXP
        27: T_ICLASS
        23: T_MODULE
         4: T_FLOAT
         4: T_FILE
         3: T_STRUCT
         2: T_BIGNUM
         1: T_COMPLEX
  All objects:
     8,159: String
     1,019: Array
       708: RubyVM::InstructionSequence
       282: Class
       153: Hash
       133: Gem::Version
       115: Gem::StubSpecification
       112: Gem::StubSpecification::StubLine
       100: Encoding
        85: Gem::Requirement
        68: Regexp
        43: Gem::Dependency
        29: Time
        23: Module
        20: Gem::Specification
        17: Proc
        12: RubyVM::Env
         9: Thread::Pool::Task
         8: MatchData
         7: Mutex
         5: Thread::Backtrace
         5: Thread
         4: Float
         3: IO
         3: Object
         2: Bignum
         2: Thread::ConditionVariable
         1: File
         1: Complex
         1: ThreadGroup
         1: IOError
         1: Binding
         1: RubyVM
         1: NoMemoryError
         1: SystemStackError
         1: Random
         1: ARGF.class
         1: Data
         1: fatal
         1: Thread::Pool
         1: Range
         1: Gem::Platform
         1: Monitor
         1: Gem::PathSupport
  String 158,055 bytes
   Array 4 elements
    Hash 1 pairs
```

**Comment by forresty** [comment]
hmm

I've rerun the test with `pool.wait`, and more aggressive mode:

```ruby
loop do
  1000.times { |i| pool.wait.process(i) }

  GC.start
end
```

the output seems good

```shell
 205: Gem::StubSpecification::StubLine
 204: Gem::Requirement
 169: Thread::Pool::Task
 124: Gem::Dependency
```

without `pool.wait`

```shell
13,508: Array
11,261: Thread::Pool::Task
10,420: String
 5,329: Time
```

Therefore I think the problem is very likely to be within my code, I will check it out, closing this now.

Thanks so much for the quick response! :smile:

**Comment by meh** [comment]
Yeah, you'll have to block somewhere along the line, or you're just going to starve the pool with unprocessed tasks, even with futures.

For instance, tasks aren't that heavy memory wise, but I'd be worried about the truckload of `Mutex` instances, but a `Future` needs a `Mutex` each.

**Comment by forresty** [comment]
But it is does not seem like that our tasks are unprocessed, otherwise there will be very noticeable problems

From the live dump the `Proc:109429` is suspicious though:

```shell
127.0.0.1:5444> gc
OK
127.0.0.1:5444> info objspace
# Objspace
TOTAL:761795
FREE:194052
T_OBJECT:143445
T_CLASS:2485
T_MODULE:271
T_FLOAT:11
T_STRING:37242
T_REGEXP:1153
T_ARRAY:93067
T_HASH:4516
T_STRUCT:57
T_BIGNUM:260
T_FILE:652
T_DATA:277363
T_MATCH:5
T_COMPLEX:1
T_RATIONAL:1
T_SYMBOL:129
T_NODE:6813
T_ICLASS:272

# Allobjects
Proc:109429
RubyVM::Env:98131
Hector::Channel:84566
Array:64515
String:37242
Time:29029
Mutex:24362
Thread::Pool::Task:24276
Thread::Future:24247
RubyVM::InstructionSequence:8440
Hash:4455
Thread::Backtrace:3821
Hector::User:3512
```

**Comment by forresty** [comment]
OK I will dig into the problem and report back if I've found something interesting. Thanks for the time! @meh

**Comment by meh** [comment]
Yeah, that number does definitely seem way too big, it may be a problem with the interaction between `Pool` and `Future`.

I'll dig more on my side as well.

**Comment by meh** [comment]
Ok, I confirm the problem is with `Future`, made a small test and it shows.

**Comment by forresty** [comment]
hmm

in https://github.com/meh/ruby-thread/blob/master/lib/thread/future.rb#L35

When there is a pool, the `@thread` is a `Thread::Pool::Task` not a `Thread`. Is this the problem?

**Comment by meh** [comment]
Yes, the problem is `task` calls `self.deliver`, and `@thread` is a `Task` which is kept alive in the finalizer.

Just trying to figure out what to do.

**Comment by forresty** [comment]
I've tested with

```ruby
if pool
  pool.process(&task)
else
  @thread = Thread.new(&task)

  ObjectSpace.define_finalizer self, self.class.finalizer(@thread)
end
```

and fixed this. Maybe I can provide a pull request?

**Comment by forresty** [comment]
hmm not quite right, `cancel` depends on the `@thread` ivar.

I'd wait for your fix then

**Comment by meh** [comment]
Yeah, working on it.

**Comment by meh** [comment]
Can you test master please? The small testcase seems to be fixed.

**Comment by forresty** [comment]
@meh deployed to our production server, seems like the correct fix

will report back later, thanks!

**Comment by forresty** [comment]
After ~10 hour the objects inside one of our processes looks like:

```shell
...
Regexp:666
Time:657
Gem::Requirement:423
Hector::User:347
Gem::Dependency:279
Module:271
Bignum:243
AVLTree::Node:241
Mutex:194
Gem::Version:148
Symbol:129
WeakRef:126
Encoding:100
Thread::Pool::Task:93
TCPSocket:89
Redis::Connection::Ruby:80
Redis::Client::Connector:80
Redis::Client:80
...
```

I believe that this bug is fixed. Thanks very much.

**Comment by meh** [comment]
Cool, I'll release the gem then.
